/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_surevine_spiffing_Spif */

#ifndef _Included_com_surevine_spiffing_Spif
#define _Included_com_surevine_spiffing_Spif
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
