/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_surevine_spiffing_Label */

#ifndef _Included_com_surevine_spiffing_Label
#define _Included_com_surevine_spiffing_Label
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_surevine_spiffing_Label
 * Method:    displayMarking
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_surevine_spiffing_Label_displayMarking
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    fgColour
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_surevine_spiffing_Label_fgColour
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    bgColour
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_surevine_spiffing_Label_bgColour
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    toESSBase64
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_surevine_spiffing_Label_toESSBase64
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_surevine_spiffing_Label_valid
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_surevine_spiffing_Label_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    dispose_n
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_surevine_spiffing_Label_dispose_1n
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Label
 * Method:    policy_n
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_surevine_spiffing_Label_policy_1n
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
