/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_surevine_spiffing_Site */

#ifndef _Included_com_surevine_spiffing_Site
#define _Included_com_surevine_spiffing_Site
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_surevine_spiffing_Site
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_surevine_spiffing_Site_init
  (JNIEnv *, jobject);

/*
 * Class:     com_surevine_spiffing_Site
 * Method:    spif_native
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_surevine_spiffing_Site_spif_1native
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_surevine_spiffing_Site
 * Method:    load_native
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_surevine_spiffing_Site_load_1native
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_surevine_spiffing_Site
 * Method:    dispose_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_surevine_spiffing_Site_dispose_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
