/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_surevine_spiffing_Spif */

#ifndef _Included_com_surevine_spiffing_Spif
#define _Included_com_surevine_spiffing_Spif
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_surevine_spiffing_Spif
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_surevine_spiffing_Spif_name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
